name: generate-install-test-deploy.yaml
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install @openapitools/openapi-generator-cli -g
      - run: openapi-generator-cli version-manager set 5.3.1
      - run: npx @openapitools/openapi-generator-cli generate -c openapi-generator-configuration.yaml
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install -r test-requirements.txt
      - name: Run tests
        run: pytest .