name: get-openapi
description: Get an OpenApi spec, save to file, and output the version and dispatch requests.
inputs:
  openapi-url:
    required: true
    description: The url to the OpenApi spec.
  file-name:
    required: false
    description: For saving the file.
    default: openapi.json
  username:
    required: false
    description: For Basic Authentication.
  password:
    required: false
    description: For Basic Authentication.
  token:
    required: false
    description: For Token Authentication.
  authentication:
    required: false
    description: Token, Basic or None Authentication types.
outputs:
  x-openapi-generator:
    description: The x-openapi-generator json string.
    value: ${{ steps.set-extension-string.outputs.extension }}
  version:
    description: The version of the openapi object.
    value: ${{ steps.set-version.outputs.version }}
runs:
  using: composite
  steps:
      - uses: ethan92429/download-file-action@master
        id: get-file
        with:
          file-url: ${{ inputs.openapi-url }}
          file-name: openapi.json
          authentication: ${{ inputs.authentication }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
          token: ${{ inputs.token }}
      - name: Set version based on the file config.
        run: |
          echo ::set-output name=version::`perl -lne 'print $1 if /version": "([\w|.|-]+)/' < openapi-config.yaml`
        shell: bash