additionalProperties:
  packageName: onshape_client.oas
  projectName: oas
  packageUrl: ""
  sortParamsByRequiredFlag: true
  hideGenerationTimestamp: true
  library: urllib3
generatorName: python
outputDir: generated/python