name: generate-install-test-deploy.yaml
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install @openapitools/openapi-generator-cli -g
      - run: openapi-generator-cli version-manager set 5.3.1
      - run: npx @openapitools/openapi-generator-cli generate -o . -g python -i https://cad.onshape.com/api/openapi --skip-validate-spec