name: generate-pr
on:
  workflow_call:
    inputs:
      openapi-url:
        type: string
        description: The URL of the OpenApi spec to generate from.
        required: true
      command-args:
        type: string
        required: false
        description: Extra command arguments for the OpenApi generate step.
    secrets:
      DEPLOY_REPO_TOKEN:
        description: The authentication token needed to create the PR in the deploy repo.
        required: false
      OPENAPI_ACCESS_TOKEN:
        description: The token needed to access the OpenApi specification.
        required: false
jobs:
  generate-pr:
    runs-on: ubuntu-latest
    env:
      OPENAPI_URL: ${{ inputs.openapi-url }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Add `openapi-generator-cli` to path
        uses: ethan92429/setup-openapi-generator-cli@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPOSITORY }}
      - name: Set GENERATOR_NAME based on the file config.
        run: |
          echo GENERATOR_NAME=`perl -lne 'print $1 if /generatorName: ([\w|-]+)/' < openapi-config.yaml` >> $GITHUB_ENV
      - uses: ethan92429/openapi-generator-workflows/.github/actions/get-openapi@main
        id: download-openapi
        with:
          openapi-url: ${{ env.OPENAPI_URL }}
          file-name: openapi.json
          token: ${{ secrets.OPENAPI_ACCESS_TOKEN }}
          authentication: Token
      - name: Install the OpenAPITools Generator CLI
        uses: eak24/setup-openapi-generator-cli@v1
      - name: Generate Client
        run: openapi-generator-cli generate -g ${{ env.GENERATOR_NAME }} -c openapi-config.yaml -i openapi.json -o . --skip-validate-spec ${{ inputs.command-args }}
      - name: Cleanup OpenApi.
        run: rm openapi.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.download-openapi.outputs.version }}
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          delete-branch: true
          commit-message: Update to version ${{ steps.download-openapi.outputs.version }}.
          title: Version ${{ steps.download-openapi.outputs.version }}
          body: The automatically generated changes created by OpenApi Generator.
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash