name: get-openapi
on:
  workflow_call:
    inputs:
      openapi-url:
        required: true
        type: string
        description: The URL to download from.
    secrets:
      username:
        required: false
        description: Username for basic authentication when fetching the spec.
      password:
        required: false
        description: Password for basic authentication when fetching the spec.
env:
  OPENAPI_URL: ${{ inputs.openapi-url }}
  VERSION: Undefined
jobs:
  get-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ethan92429/openapi-generator-workflows/.github/actions/get-openapi@main
        id: get-openapi
        with:
          openapi-url: ${{ env.OPENAPI_URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          authentication: Basic
      - name: Prettify Json
        run: |
          python -m json.tool openapi.json > pretty_openapi.json
          mv pretty_openapi.json openapi.json
      - name: Download PostProcessor Code
        uses: ethan92429/download-file-action@master
        with:
          file-url: https://raw.githubusercontent.com/ethan92429/openapi-generator-workflows/main/scripts/postprocess.py
          location: ../scripts
      - name: PostProcess Json
        run: |
          python -m ../scripts/postprocess.py openapi.json postprocess_config.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.get-openapi.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: Update to version ${{ steps.get-openapi.outputs.version }}.
          title: Version ${{ steps.get-openapi.outputs.version }}
          body: The automatically generated changes created by OpenApi Generator for the update to version ${{ steps.get-openapi.outputs.version }}.