name: get-openapi
on:
  workflow_dispatch:
    openapi-url:
      description: The URL to download from.
    username:
      description: Username for basic authentication when fetching the spec.
    password:
      description: Password for basic authentication when fetching the spec.
env:
  OPENAPI_URL: ${{ github.event.inputs.openapi-url }}
  USERNAME: ${{ github.event.inputs.username }}
  PASSWORD: ${{ github.event.inputs.password }}
  VERSION: Undefined
jobs:
  get-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ethan92429/onshape-generator/.github/actions/get-openapi@master
        id: get-openapi
        with:
          file-url: ${{ env.OPENAPI_URL }}
          file-name: openapi.json
          authentication: Basic
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add openapi.json
          git commit -m "OpenApi ${{ steps.get-openapi.outputs.version }}" -a
          git tag -a ${{ steps.get-openapi.outputs.version }} -m "Version ${{ steps.get-openapi.outputs.version }} from ${{ env.OPENAPI_URL }}"
      - name: Deploy
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}